[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/free"
  to = "/free.html"
  status = 200

[[redirects]]
  from = "/color"
  to = "/color.html"
  status = 200
